#!/bin/bash

PN="${BASH_SOURCE[0]##*/}"
PD="${BASH_SOURCE[0]%/*}"

source "${PD}/lib/die"

function usage() {
	cat <<EOF
Usage: ${PN} [Options] <Commit>
Options:
  -h       : show this help message
  -f       : force push

Commit:
  Commit hash value
EOF
	[ $# -gt 0 ] && { echo ; die "$@" ; } || exit 0
}

type getopt cat grep cut git >/dev/null || exit $?

(($# == 0)) && usage "Invalid parameters"
opt="$(getopt -o hf -- "$@")" || usage "Parse options failed"

eval set -- "${opt}"
while true ; do
	case "${1}" in
	-h) usage ; shift ;;
	-f) force_push=1 ; shift ;;
	--) shift ; break ;;
	*) echo "Internal error!" ; exit 1 ;;
	esac
done

(($# < 1)) && usage "Invalid parameters"

push_commit="${1}"
shift

# check is in git repository
msg="$(git branch 2>&1)"
if [ $? -ne 0 ] ; then
	echo "${msg}"
	exit 1
fi

# get some status
cur_branch="$(grep "^*" <<<"${msg}" | cut -b 3-)"
cur_remote="$(git config --get "branch.${cur_branch}.remote")"
cur_merge="$(git config --get "branch.${cur_branch}.merge")"

[ "${cur_remote}" ] || die "Empty remote branch"
[ "${cur_merge}" ] || die "Empty merge branch"

if [ "${force_push}" == "1" ] ; then
	git push "${cur_remote}" "+${push_commit}:${cur_merge}" || die
else
	git push "${cur_remote}" "${push_commit}:${cur_merge}" || die
fi

