#!/bin/bash

PN="${BASH_SOURCE[0]##*/}"
PD="${BASH_SOURCE[0]%/*}"

source "${PD}/lib/common"

function usage() {
	cat <<EOF
Usage: ${PN} [Options] [Input path]
Options:
  -h       : show this help message
  -D <DIR> : set output dir
  -f       : compress in fast mode (effect in t7z mode)
  -t       : add time suffix (Ex: OUTPUT-19991231.7z)

Default input path: "."
Default output dir: dirname of input path
EOF
	[ $# -gt 0 ] && { echo ; die "$@" ; } || exit 0
}

case "${PN}" in
t7z) neccmd 7z ;;
*) neccmd tar ;;
esac

opt="$(getopt -o hD:ft -- "$@")" || usage "Parse options failed"

eval set -- "${opt}"
while true ; do
	case "${1}" in
	-h) usage ;;
	-D) tdir="${2%%/}" ; shift 2 ;;
	-f) fastmode=1 ; shift ;;
	-t) timesuffix=1 ; shift ;;
	--) shift ; break ;;
	*) die "Internal error!" ;;
	esac
done

src="$(readlink -f "${1:-.}")"
[ "${src}" == "/" ] && die "Input path cannot be '/'"

d="${src%/*}"
src="${src##*/}"
tar="${src}"

if [ "${timesuffix}" == "1" ] ; then
	tar="${tar}-$(date "+%Y%m%d")"
fi

if [ "${PN}" == "t7z" ] ; then
	tar="${tar}.7z"
else
	tar="${tar}.tbz"
fi

if [ "${tdir}" ] ; then
	tar="${tdir}/${tar}"
else
	tar="${d}/${tar}"
fi

pushd "${d}" &>/dev/null

[ -e "${src}" ] || die "'${src}' not found"
[ -e "${tar}" ] && die "Target file '${tar}' exists"

echo "${PWD}"
if [ "${PN}" == "t7z" ] ; then
	if [ "${fastmode}" == 1 ] ; then
		7z a -m0=lzma -mx=3 -mfb=273 -md=32m "${tar}" "${src}"
	else
		7z a -m0=lzma -mx=9 -mfb=273 -md=32m "${tar}" "${src}"
	fi
else
	tar cjvpf "${tar}" "${src}"
fi
echo
echo "output: ${tar}"

popd &>/dev/null

