#!/bin/bash
# useful functions:
#   gcd <num1> <num2>

if ! type gcd >/dev/null 2>&1 ; then

# $1 := number 1
# $2 := number 2
gcd() {
	local dividend="${1}"
	local divisor="${2}"
	local remainder=1

	until [ "$remainder" -eq 0 ]
	do
		let "remainder = $dividend % $divisor"
		dividend="${divisor}"
		divisor="${remainder}"
	done
	echo "${dividend}"
}

fi # ! type gcd

