#!/bin/bash
# useful variables:
#	SINGLEAPP_LOCK_FILE
#	SINGLEAPP_USER_PREFIX
#	SINGLEAPP_USER_SUFFIX
# useful functions:
#   single_app_on_exit

if ! type check_single_app >/dev/null 2>&1 ; then

PD="${BASH_SOURCE[0]%/*}"
source "${PD}/common" || exit 1
source "${PD}/layout.sh" || exit 1
source "${PD}/handle_out" || exit 1

check_single_app() {
	local c="${#BASH_SOURCE[@]}"
	local i="$((c-1))"
	local pn="${BASH_SOURCE[${i}]##*/}"
	local prefix="/tmp/_singleapp_lock_file_${SINGLEAPP_USER_PREFIX}"
	local suffix="${SINGLEAPP_USER_SUFFIX}"
	local lock_file="${SINGLEAPP_LOCK_FILE:=${prefix}${pn}${suffix}}"
	local pid

	if [ -e "${lock_file}" ] ; then
		pid="$(cat "${lock_file}")"
		if [ "${pid}" ] && [ -d "/proc/${pid}/" ] ; then
			die "Another app executed, pid: '${pid}', from: '${lock_file}'"
		else
			ewarn "lock file exists, but no process found, ${pid}: ${lock_file}"
			pushd /proc/self >/dev/null ; cut -d' ' -f1 stat > "${lock_file}" ; popd >/dev/null
		fi
	else
		pushd /proc/self >/dev/null ; cut -d' ' -f1 stat > "${lock_file}" ; popd >/dev/null
	fi
}
check_single_app

single_app_on_exit() {
	rm -f "${SINGLEAPP_LOCK_FILE}"
}
insert_exit single_app_on_exit


poparg
fi # ! type check_single_app

